config/routes.rb
Rails.application.routes.draw do
  get 'charts_data/full_chart_data'
  get 'charts_data/full_chart_check_points'
  get 'charts_data/big_chart_data'
  get 'charts_data/other_chart_data'
  get 'charts_data/sorted_full_chart_data'
  get 'charts_data/products_characteristics'

  apipie

  devise_for :users, skip: [:session, :password, :registration, :confirmation],
      controllers: { omniauth_callbacks: 'customized_devise/omniauth_callbacks' }

  scope "(:locale)", locale: /en|ru/ do
    root 'welcome#index'
    get 'dashboard' => 'dashboard#index', as: :dashboard
    get 'templates(/*url)' => 'application#templates'
    get 'apidocs' => 'apidocs#index'

    devise_for :users, controllers: {
        registrations: 'customized_devise/registrations',
        sessions: 'customized_devise/sessions',
        passwords: 'customized_devise/passwords'
    }, skip: :omniauth_callbacks

    devise_scope :user do
      match 'users/avatar' => 'customized_devise/registrations#avatar', via: [:put, :patch]
    end

    scope :subscriptions do
      get 'callback' => 'subscriptions#callback', as: :subscription_callback
      get ':id' => 'subscriptions#show', as: :show_subscription
      post 'change' => 'subscriptions#change', as: :change_subscription
    end

    scope :profile do
      post 'email_uniqueness' => 'profile#email_uniqueness'
      get  '/' => 'profile#index', as: :profile
      post '/' => 'profile#update', as: :update
    end

    resources :projects, defaults: { format: :json } do
      collection do
        post 'search' => 'projects#search'
      end
      resources :permissions, only: [:index, :update, :destroy], shallow: true, on: :member
      resources :pending_permissions, only: [:create, :destroy], on: :member
      resources :items, only: [:index, :create, :update, :destroy], on: :member do
        delete :values, on: :member
      end
      resources :forecasts, only: [:new, :create] do
        resources :predicted_values, only: :index
      end
      resources :attachments, only: :create
      get :full_chart, on: :member
    end

    resources :permissions, only: :index do
      get :activate, on: :member
    end
  end
end

load Rails.root.join 'config/routes/api.rb'
load Rails.root.join 'config/routes/admin.rb'
load Rails.root.join 'config/routes/third_party.rb'

app/views/popups/_api_status.html.slim
.hidden
  #modal-api-status.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-login
        .modal-capt=t '.title'
        .modal-cnt
          p
            =t '.description.line_1'
            = t('.description.line_2', manual_url: '/apidocs', email_url: 'mailto:support@dynamica.cc').html_safe
          .form-group
            .control-box
              .descript=t '.api_token'
            .control-box
              = text_field_tag :api_token, current_user.api_token, class: 'form-control', readonly: true
          .descript
            br/
            - last_api_request = @project.logs.order(id: :asc).includes(:user).first
            - if last_api_request
              p.text-center
                = t('.last_request', date: I18n.l(last_api_request.created_at, format: :long), user: last_api_request.user.display_name).html_safe
            - else
              p.text-center=t '.no_requests'

app/views/popups/_api_used.html.slim
.hidden
  #modal-api-used.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-login
        .modal-capt=t '.title'
        .modal-cnt
          .form
            .descript
              =t '.description.line_1'
              br/
              br/
              =t '.description.line_2'
              br/
              br/
            .form-group
              .control-box.text-center
                = link_to t('.button_no'), '#', class: 'btn btn-lg btn-danger arcticmodal-close'
              .control-box.text-center.clear
                = link_to t('.button_yes'), new_project_forecast_path(@project)

app/views/popups/_auth.haml
#auth_popup.modal.fade(role = "dialog")
  .modal-dialog.modal_v1
    .modal-content
      .modal-header
        .modal-title
          %span.dynamica_loading
          %span Dynamica importing data from your Shopify
      .modal-body
        %h3
          To see
          = succeed "analytics" do
            %span.fw_700 Bling-Blings
          you need sign up
      .modal-soc_auth
        .control-box
          %a.btn-social-auth.btn-facebook(href="#{user_omniauth_authorize_url(:facebook)}")
            %i.icon.fa.fa-facebook>
            Facebook
        .control-box
          %a.btn-social-auth.btn-google(href="#{user_omniauth_authorize_url(:google_oauth2)}")
            %i.icon.fa.fa-google-plus>
            Google plus
      .form_holder
        %form(action = user_session_path method='POST')
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .alternal_auth= t('landing.auth_popup.enter_mail_manually')
          .control-box
            %input.form-control(placeholder = "#{t('landing.auth_popup.email')}" type = "text" ng-model='vm.sign_in_email')
          .control-box
            %input.form-control(placeholder = "#{t('landing.auth_popup.password')}" type = "password" ng-model='vm.sign_in_password')
          .control-box.text-center.btn_holder
            %button.btn.btn-lg.btn-danger(ng-click = "vm.sign_in(vm.sign_in_email, vm.sign_in_password)")= t('landing.auth_popup.go')
          .control-box.text-center.btn_holder
            %a.btn-link.forgot_pass_link(href = "" ng-click="vm.modal('restore_pass_popup','show')")= t('landing.auth_popup.i_forgot_password')

app/views/popups/_confirm_address.haml
#confirm_address_popup.modal.fade(role = "dialog")
  .modal-dialog.modal_v1
    / Modal content
    .modal-content
      .modal-header
        .modal-title &nbsp;
      .modal-body.text-center
        %p
          Confirm your email address
          %br
            %span.address yaosamo@gmail.com
      .form_holder
        .control-box.text-center.btn_holder
          %a.btn-link{:href => "#"} Ok, thanks!

app/views/popups/_creating_graph.html.slim
.page-overlay.creatingGraphPopup
  .popup_info.no_server_popup
    a.popup_close href="#"
      i.icon.fa.fa-times
    .popup_inner
      .popup_icon
        .dynamica_icon
          svg height="86px" version="1.1" viewbox=("0 0 96 86") width="96px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"

    /! Generator: sketchtool 3.6.1 (26313) - http://www.bohemiancoding.com/sketch
            title icon
            desc Created with sketchtool.
            defs
            g#Page-1 fill="none" fill-rule="evenodd" stroke="none" stroke-width="1"
              g#Dashboard-empty fill="#FF6140" transform="translate(-602.000000, -432.000000)"
                g#icon transform="translate(602.000000, 432.000000)"
                  path#Fill-1 d="M10.0005,4 C6.6915,4 4.0005,6.691 4.0005,10 L4.0005,76 C4.0005,79.309 6.6915,82 10.0005,82 L86.0005,82 C89.3095,82 92.0005,79.309 92.0005,76 L92.0005,10 C92.0005,6.691 89.3095,4 86.0005,4 L10.0005,4 Z M86.0005,86 L10.0005,86 C4.4865,86 0.0005,81.514 0.0005,76 L0.0005,10 C0.0005,4.486 4.4865,0 10.0005,0 L86.0005,0 C91.5145,0 96.0005,4.486 96.0005,10 L96.0005,76 C96.0005,81.514 91.5145,86 86.0005,86 L86.0005,86 Z"
                  path#Fill-3 d="M28.0005,45 C27.4485,45 27.0005,45.449 27.0005,46 C27.0005,46.551 27.4485,47 28.0005,47 C28.5525,47 29.0005,46.551 29.0005,46 C29.0005,45.449 28.5525,45 28.0005,45 M28.0005,51 C25.2435,51 23.0005,48.757 23.0005,46 C23.0005,43.243 25.2435,41 28.0005,41 C30.7575,41 33.0005,43.243 33.0005,46 C33.0005,48.757 30.7575,51 28.0005,51"
                  path#Fill-5 d="M13.0005,59 C12.4485,59 12.0005,59.449 12.0005,60 C12.0005,60.551 12.4485,61 13.0005,61 C13.5525,61 14.0005,60.551 14.0005,60 C14.0005,59.449 13.5525,59 13.0005,59 M13.0005,65 C10.2435,65 8.0005,62.757 8.0005,60 C8.0005,57.243 10.2435,55 13.0005,55 C15.7575,55 18.0005,57.243 18.0005,60 C18.0005,62.757 15.7575,65 13.0005,65"
                  path#Fill-7 d="M83.0005,45 C82.4485,45 82.0005,45.449 82.0005,46 C82.0005,46.551 82.4485,47 83.0005,47 C83.5525,47 84.0005,46.551 84.0005,46 C84.0005,45.449 83.5525,45 83.0005,45 M83.0005,51 C80.2435,51 78.0005,48.757 78.0005,46 C78.0005,43.243 80.2435,41 83.0005,41 C85.7575,41 88.0005,43.243 88.0005,46 C88.0005,48.757 85.7575,51 83.0005,51"
                  path#Fill-9 d="M40.0005,52 C39.4485,52 39.0005,52.449 39.0005,53 C39.0005,53.551 39.4485,54 40.0005,54 C40.5525,54 41.0005,53.551 41.0005,53 C41.0005,52.449 40.5525,52 40.0005,52 M40.0005,58 C37.2435,58 35.0005,55.757 35.0005,53 C35.0005,50.243 37.2435,48 40.0005,48 C42.7575,48 45.0005,50.243 45.0005,53 C45.0005,55.757 42.7575,58 40.0005,58"
                  path#Fill-11 d="M52.0005,42 C51.4485,42 51.0005,42.449 51.0005,43 C51.0005,43.551 51.4485,44 52.0005,44 C52.5525,44 53.0005,43.551 53.0005,43 C53.0005,42.449 52.5525,42 52.0005,42 M52.0005,48 C49.2435,48 47.0005,45.757 47.0005,43 C47.0005,40.243 49.2435,38 52.0005,38 C54.7575,38 57.0005,40.243 57.0005,43 C57.0005,45.757 54.7575,48 52.0005,48"
                  path#Fill-13 d="M67.0005,35 C66.4485,35 66.0005,35.449 66.0005,36 C66.0005,36.551 66.4485,37 67.0005,37 C67.5525,37 68.0005,36.551 68.0005,36 C68.0005,35.449 67.5525,35 67.0005,35 M67.0005,41 C64.2435,41 62.0005,38.757 62.0005,36 C62.0005,33.243 64.2435,31 67.0005,31 C69.7575,31 72.0005,33.243 72.0005,36 C72.0005,38.757 69.7575,41 67.0005,41"
                  path#Fill-15 d="M36.9986,53.667 C36.6716,53.667 36.3396,53.586 36.0326,53.417 L29.3106,49.7 C28.3436,49.165 27.9926,47.948 28.5276,46.981 C29.0616,46.015 30.2806,45.666 31.2456,46.199 L37.9686,49.916 C38.9356,50.451 39.2856,51.667 38.7506,52.634 C38.3866,53.294 37.7026,53.667 36.9986,53.667"
                  path#Fill-17 d="M42.0425,52.8052 C41.4705,52.8052 40.9005,52.5602 40.5055,52.0862 C39.7985,51.2382 39.9125,49.9772 40.7605,49.2692 L47.7195,43.4642 C48.5665,42.7572 49.8285,42.8702 50.5365,43.7192 C51.2435,44.5672 51.1295,45.8282 50.2815,46.5352 L43.3225,52.3412 C42.9485,52.6532 42.4945,52.8052 42.0425,52.8052"
                  path#Fill-19 d="M54.4185,43.229 C53.6395,43.229 52.8985,42.771 52.5755,42.009 C52.1455,40.992 52.6195,39.818 53.6375,39.387 L63.2205,35.325 C64.2385,34.893 65.4115,35.37 65.8425,36.386 C66.2725,37.403 65.7985,38.577 64.7805,39.008 L55.1975,43.07 C54.9425,43.178 54.6785,43.229 54.4185,43.229"
                  path#Fill-21 d="M16.4995,59.25 C16.0185,59.25 15.5345,59.077 15.1505,58.727 C14.3355,57.981 14.2785,56.716 15.0235,55.901 L23.5235,46.6 C24.2685,45.785 25.5325,45.727 26.3505,46.473 C27.1655,47.218 27.2225,48.483 26.4775,49.298 L17.9775,58.599 C17.5825,59.031 17.0425,59.25 16.4995,59.25"
                  path#Fill-23 d="M80.7671,46 C80.3531,46 79.9351,45.872 79.5771,45.605 L68.8081,37.605 C67.9211,36.947 67.7361,35.694 68.3951,34.807 C69.0531,33.921 70.3061,33.736 71.1931,34.395 L81.9611,42.395 C82.8481,43.053 83.0341,44.306 82.3741,45.193 C81.9821,45.721 81.3781,46 80.7671,46"
                  path#Fill-25 d="M94.0005,48 L86.0005,48 C84.8965,48 84.0005,47.104 84.0005,46 C84.0005,44.896 84.8965,44 86.0005,44 L94.0005,44 C95.1045,44 96.0005,44.896 96.0005,46 C96.0005,47.104 95.1045,48 94.0005,48"
                  path#Fill-27 d="M1.9986,65.0005 C1.1026,65.0005 0.2876,64.3945 0.0606,63.4845 C-0.2074,62.4135 0.4436,61.3275 1.5156,61.0595 L9.5156,59.0595 C10.5856,58.7945 11.6726,59.4425 11.9406,60.5155 C12.2086,61.5865 11.5576,62.6725 10.4856,62.9405 L2.4856,64.9405 C2.3226,64.9805 2.1596,65.0005 1.9986,65.0005"
      .popup_content
        .popup_caption We creating graphs and analytics for you
        p Please wait, it can take about 20 mins
      .popup_controls
        a.btn.btn-lg.btn-danger href="#"  Back to my projects

app/views/popups/_csv_example.html.slim
.hidden
  #modal-csv-example.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href="#"  &times;
      section.modal-instruct
        .modal-capt=t '.title'
        .modal-cnt
          .title=t '.subtitle'
          .format-items
            .row
              .col-sm-6
                .format-item
                  .format-title=t '.two_columns'
                  figure
                    = image_tag 'table1.png', width: '400', height: 146
              .col-sm-6
                .format-item
                  .format-title=t '.two_rows'
                  figure
                    = image_tag 'table2.png', width: '400', height: 146
          .title=t '.text_bottom'
          .note-items
            .row.text-center
              .col-sm-6
                .note-item
                  .note-title=t '.example_1.title'
                  .download
                    a href='/csv-examples/product_orders.csv' target='_blank'=t '.example_1.download'
              .col-sm-6
                .note-item
                  .note-title=t '.example_2.title'
                  .download
                    a href='/csv-examples/exchange_rates.csv' target='_blank'=t '.example_2.download'
          .form
            .form-group
              .control-box.text-center
                = link_to t('.ok'), '#', class: 'btn btn-lg btn-danger arcticmodal-close'

app/views/popups/_login.html.slim
.hidden
  #modal-login.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-login
        .modal-capt
          ul.nav.nav-pills
            li.active
              a=t '.log_in.log_in'
            li
              a href='#' data-modal='signup'=t '.log_in.sign_up'
        .modal-cnt
          .form
            = form_for User.new, as: :user, url: session_path(:user), html: { class: 'validate-login form-horizontal' }, remote: true do |f|
              / .form-group.clearfix
                .control-box
                  a.btn-social.btn-facebook href='#' 
                    i.icon.fa.fa-facebook
                    | Facebook
                  a.btn-social.btn-twitter href='#' 
                    i.icon.fa.fa-twitter
                    | Twitter
              .form-group
                .control-box
                  = f.email_field :email, class: 'form-control', autofocus: true, placeholder: t('.log_in.form.email')
                .control-box
                  = f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: t('.log_in.form.password')
                .control-box.text-center
                  = f.submit t('.log_in.form.submit'), class: 'btn btn-lg btn-danger'
                .control-box.text-center.clear
                  a href='#' data-modal='recover'=t '.log_in.password_recovery'

  #modal-signup.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-login
        .modal-capt
          ul.nav.nav-pills
            li
              a href='#' data-modal='login'=t '.sign_up.log_in'
            li.active
              a=t '.sign_up.sign_up'
        .modal-cnt
          .form
            = form_for User.new, as: :user, url: registration_path(:user), html: { class: 'validate-signup form-horizontal' }, remote: true do |f|
              .form-group
                .control-box
                  = f.email_field :email, class: 'form-control', autofocus: true, placeholder: t('.sign_up.form.email')
                .control-box
                  = f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: t('.sign_up.form.password')
                .control-box.text-center
                  = f.submit t('.sign_up.form.submit'), class: 'btn btn-lg btn-danger'
                .control-box.text-center.clear
                  a href="https://myshopify.com/admin/oauth/authorize?client_id=#{Dynamica::Settings::Shopify.api_key}&scope=read_orders,read_customers,read_products&redirect_uri=#{Dynamica::Settings::Shopify.redirect_url}&state=#{SecureRandom.hex}"= t('.sign_up.with_shopify')

  #modal-recover.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-login
        .modal-capt
          ul.nav.nav-pills
            li
              a href='#' data-modal='login'=t '.password_recovery.back'
            li.active
              a=t '.password_recovery.password_recovery'
        .modal-cnt
          .form
            = form_for User.new, as: :user, url: password_path(:user), html: { class: 'validate-password-recovery', method: :post }, remote: true do |f|
              .form-group
                .control-box
                  .descript
                    =t '.password_recovery.description.line_1'
                    br/
                    =t '.password_recovery.description.line_2'
                .control-box
                  = f.email_field :email, class: 'form-control', autofocus: true, placeholder: t('.password_recovery.form.email')
                .control-box.text-center
                  = f.submit t('.password_recovery.form.submit'), class: 'btn btn-lg btn-danger'

  #modal-password-recovery-sent.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-confirm
        .modal-cnt
          .descript
            br/
            p
              =t '.password_recovery_sent.description'
              br/
              span.email
          .accept
            p
              a.arcticmodal-close href='#'=t '.password_recovery_sent.ok'

  #modal-password-new.box-modal
    .box-modal_i
      a.box-modal_close.arcticmodal-close href='#'  &times;
      section.modal-login
        .modal-capt
          ul.nav.nav-pills
            li.active
              a=t '.password_new.title'
        .modal-cnt
          .form
            = form_for User.new, as: :user, url: password_path(:user), html: { class: 'validate-password-new', method: :put }, remote: true do |f|
              = f.hidden_field :reset_password_token, value: params[:reset_password_token]
              .form-group
                .control-box
                  = f.password_field :password, class: 'form-control', autofocus: true, autocomplete: "off", placeholder: t('.password_new.form.password')
                .control-box
                  = f.password_field :password_confirmation, class: 'form-control', autocomplete: "off", placeholder: t('.password_new.form.password_confirmation')
                .control-box.text-center
                  = f.submit t('.password_new.form.submit'), class: 'btn btn-lg btn-danger'

app/views/popups/_no_access.haml
#no_access_popup.modal.fade(role = "dialog")
  .modal-dialog.modal_v1
    / Modal content
    .modal-content
      .modal-header
        .modal-title &nbsp;
      .modal-body
        %h3
          We didn’t get
          %br
            access to your Shopify
            %br store, want to try again?
      .form_holder
        .control-box.text-center.btn_holder
          %a.btn.btn-lg.btn-danger{:href => "#"} Yes, please
        .control-box.text-center.btn_holder
          %a.btn-link.forgot_pass_link{:href => "#"} No

app/views/popups/_no_server.html.slim
.page-overlay.noServerPopup
  .popup_info.no_server_popup
    a.popup_close href="#"
      i.icon.fa.fa-times
    .popup_inner
      .popup_icon
        .no_server_icon
      .popup_content
        .popup_caption Server cannot be reach
        p
          | For some reason we can’t pull in analytics data,
          br/
          | please try again later
      .popup_controls
        a.btn.btn-lg.btn-danger href="#"  Okay

app/views/popups/_not_ready.haml
#not_ready_popup.modal.fade(role = "dialog")
  .modal-dialog.modal_v1{:style => "width: 728px;"}
    / Modal content
    .modal-content
      .modal-header
      .modal-body
        .modal_dynamica_logo.text-center
          %img{:src => "images/dynamica.svg"}/
        %h3
          Graphics are not ready yet,
          %br we can remind you
      .form_holder
        .control-box.text-center.btn_holder
          %a.btn.btn-lg.btn-danger{:href => "#"} Remind me, on email

app/views/popups/_password_sended.haml
#password_sended_popup.modal.fade(role = "dialog")
  .modal-dialog.modal_v1
    / Modal content
    .modal-content
      .modal-header
        .modal-title &nbsp;
      .modal-body.text-center
        %p= t('landing.password_sended.check_email')
        %span.address {{ vm.restore_pass_email }}
      .form_holder
        .control-box.text-center.btn_holder
          %a.btn-link(href = "" ng-click="vm.modal('password_sended_popup', 'close')")= t('landing.password_sended.ok')

app/views/popups/_restore_pass.haml
#restore_pass_popup.modal.fade(role = "dialog")
  .modal-dialog.modal_v1
    / Modal content
    .modal-content
      .modal-header
      .modal-body
        %h3= t('landing.restore_pass.password_recovery')
        %p.text-center= t('landing.restore_pass.helper_text')
      .form_holder
        %form(action = "")
          .control-box
            %input.form-control(ng-model="vm.restore_pass_email" placeholder = "#{t('landing.restore_pass.email')}" type = "text")
          .control-box
            {{vm.error_message}}
          .control-box.text-center.btn_holder
            %button.btn.btn-lg.btn-danger(ng-click="vm.restore_pass_send(vm.restore_pass_email)")= t('landing.restore_pass.restore')
          .control-box.text-center.btn_holder
            %a.btn-link.forgot_pass_link(href = "" ng-click = "vm.modal('auth_popup','show')")= t('landing.restore_pass.back')